# Copyright 2025 The game_arena Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for poker parsers."""

from game_arena.harness.games.poker import parsers
from absl.testing import absltest

import pyspiel


class ParsersTest(absltest.TestCase):

  def test_repeated_poker_soft_parser(self):
    # pylint: disable=line-too-long
    # STATE:0:r6c/c:7s8c|9dKh/Ts7dAc
    serialized_game_and_state = "# Automatically generated by OpenSpiel SerializeGameAndState\n[Meta]\nVersion: 1\n\n[Game]\nrepeated_poker(max_num_hands=5,reset_stacks=True,rotate_dealer=True,universal_poker_game_string=universal_poker(betting=nolimit,bettingAbstraction=fullgame,blind=2 1,calcOddsNumSims=1000000,firstPlayer=2 1 1 1,numBoardCards=0 3 1 1,numHoleCards=2,numPlayers=2,numRanks=13,numRounds=4,numSuits=4,stack=200 200))\n[State]\n23\n24\n29\n46\n6\n1\n35\n21\n48\n1\n\n"
    # pylint: enable=line-too-long
    _, state = pyspiel.deserialize_game_and_state(serialized_game_and_state)
    output = parsers.repeated_poker_soft_parser(
        state_str=str(state),
        selected_action="raise 4",
        legal_moves=[state.action_to_string(a) for a in state.legal_actions()],
        player_number=state.current_player(),
    )
    self.assertEqual(output, "player=1 move=Bet10")

  def test_repeated_poker_soft_parser_2(self):
    # pylint: disable=line-too-long
    # STATE:0:r6r24c/r40c/cr114c/c:8c6c|4h4c/6sTd3c/3h/4d
    serialized_game_and_state = "# Automatically generated by OpenSpiel SerializeGameAndState\n[Meta]\nVersion: 1\n\n[Game]\nrepeated_poker(max_num_hands=100,reset_stacks=True,rotate_dealer=True,universal_poker_game_string=universal_poker(betting=nolimit,bettingAbstraction=fullgame,blind=2 1,calcOddsNumSims=0,firstPlayer=2 1 1 1,numBoardCards=0 3 1 1,numHoleCards=2,numPlayers=2,numRanks=13,numRounds=4,numSuits=4,stack=200 200))\n[State]\n38\n1\n0\n17\n0\n33\n31\n23\n0\n5\n0\n51\n8\n12\n5\n0\n39\n31\n3\n50\n5\n0\n20\n25\n29\n15\n0\n33\n27\n41\n13\n5\n1\n22\n2\n16\n1\n8\n1\n49\n1\n25\n1\n26\n88\n0\n24\n16\n10\n8\n6\n24\n1\n19\n33\n4\n40\n1\n6\n1\n114\n1\n9\n1\n\n"
    # pylint: enable=line-too-long
    _, state = pyspiel.deserialize_game_and_state(serialized_game_and_state)
    output = parsers.repeated_poker_soft_parser(
        state_str=str(state),
        selected_action="bet 86",
        legal_moves=[state.action_to_string(a) for a in state.legal_actions()],
        player_number=state.current_player(),
    )
    self.assertEqual(output, "player=1 move=Bet200")
    output = parsers.repeated_poker_soft_parser(
        state_str=str(state),
        selected_action="  all in",
        legal_moves=[state.action_to_string(a) for a in state.legal_actions()],
        player_number=state.current_player(),
    )
    self.assertEqual(output, "player=1 move=Bet200")

  def test_repeated_poker_soft_parser_3(self):
    # pylint: disable=line-too-long
    game = pyspiel.load_game("repeated_poker(max_num_hands=100,reset_stacks=True,rotate_dealer=True,universal_poker_game_string=universal_poker(betting=nolimit,bettingAbstraction=fullgame,blind=2 1,calcOddsNumSims=0,firstPlayer=2 1 1 1,numBoardCards=0 3 1 1,numHoleCards=2,numPlayers=2,numRanks=13,numRounds=4,numSuits=4,stack=200 200))")
    # pylint: enable=line-too-long
    state = game.new_initial_state()
    state.apply_action(state.string_to_action("player=-1 move=Deal 8s"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 9s"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Jh"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Jd"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action=" bet 4",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet4",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet4"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="call",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Call",
    )
    state.apply_action(state.string_to_action("player=0 move=Call"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2s"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2c"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2d"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="bet 4",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet8",
    )
    state.apply_action(state.string_to_action("player=0 move=Bet8"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 8",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet12",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet12"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 20",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet24",
    )
    # We're not applying this move but checking that a raise that is too small
    # is mapped to the next legal bet. The first raise this round was to 4,
    # and the raise to 8 was 4 more than that. So any raise must be 4 more than
    # 8 = 12. Add 4 from preflop action to get 16.
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 9",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet16",
    )
    # Apply the intended move.
    state.apply_action(state.string_to_action("player=0 move=Bet24"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 44",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet48",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet48"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="call",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Call",
    )
    state.apply_action(state.string_to_action("player=0 move=Call"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2h"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 2",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet50",
    )
    state.apply_action(state.string_to_action("player=0 move=Bet50"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 5",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet53",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet53"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 10",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet58",
    )
    # Another check that a raise that is too small is mapped to the next legal
    # bet. The first bet was 2, then 5 for an increment of 3. The smallest
    # legal raise is then 5 + 3 = 8, which puts the player in for 56 total.
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 2",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet56",
    )
    state.apply_action(state.string_to_action("player=0 move=Bet58"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="callll",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Call",
    )
    state.apply_action(state.string_to_action("player=1 move=Call"))
    state.apply_action(state.string_to_action("player=-1 move=Deal As"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="check",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Call",
    )
    state.apply_action(state.string_to_action("player=0 move=Call"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 42",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet100",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet100"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 140",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet198",
    )
    state.apply_action(state.string_to_action("player=0 move=Bet198"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 142",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet200",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet200"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="all in",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Call",
    )

  # Tests correctness after hand #0 with blinds reversed.
  # Also tests reraise preflop.
  def test_repeated_poker_soft_parser_4(self):
    # pylint: disable=line-too-long
    game = pyspiel.load_game("repeated_poker(max_num_hands=100,reset_stacks=True,rotate_dealer=True,universal_poker_game_string=universal_poker(betting=nolimit,bettingAbstraction=fullgame,blind=2 1,calcOddsNumSims=0,firstPlayer=2 1 1 1,numBoardCards=0 3 1 1,numHoleCards=2,numPlayers=2,numRanks=13,numRounds=4,numSuits=4,stack=200 200))")
    # pylint: enable=line-too-long
    state = game.new_initial_state()
    state.apply_action(state.string_to_action("player=-1 move=Deal 8s"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2c"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 7h"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 3d"))
    state.apply_action(state.string_to_action("player=1 move=Fold"))
    state.apply_action(state.string_to_action("player=-1 move=Deal As"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Ac"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Kh"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Kd"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action=" bet 5",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet5",
    )
    state.apply_action(state.string_to_action("player=0 move=Bet5"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 101",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet101",
    )
    state.apply_action(state.string_to_action("player=1 move=Bet101"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="call",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Call",
    )
    state.apply_action(state.string_to_action("player=0 move=Call"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2s"))
    state.apply_action(state.string_to_action("player=-1 move=Deal 2c"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Ks"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="I want to check68798798689696",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Call",
    )
    state.apply_action(state.string_to_action("player=1 move=Call"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 98",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Bet199",
    )
    state.apply_action(state.string_to_action("player=0 move=Bet199"))
    self.assertLen(state.legal_actions(), 3)
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise all in ",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet200",
    )
    # Test that we can handle a raise that is larger than the legal range.
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action="raise 1000000000",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=1 move=Bet200",
    )

  def test_repeated_poker_soft_parser_5(self):
    # pylint: disable=line-too-long
    game = pyspiel.load_game("repeated_poker(max_num_hands=100,reset_stacks=True,rotate_dealer=True,universal_poker_game_string=universal_poker(betting=nolimit,bettingAbstraction=fullgame,blind=2 1,calcOddsNumSims=0,firstPlayer=2 1 1 1,numBoardCards=0 3 1 1,numHoleCards=2,numPlayers=2,numRanks=13,numRounds=4,numSuits=4,stack=200 200))")
    # pylint: enable=line-too-long
    state = game.new_initial_state()
    state.apply_action(state.string_to_action("player=-1 move=Deal As"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Ac"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Kh"))
    state.apply_action(state.string_to_action("player=-1 move=Deal Kd"))
    state.apply_action(state.string_to_action("player=1 move=Bet200"))
    self.assertEqual(
        parsers.repeated_poker_soft_parser(
            state_str=str(state),
            selected_action=" bet 5",
            legal_moves=[
                state.action_to_string(a) for a in state.legal_actions()
            ],
            player_number=state.current_player(),
        ),
        "player=0 move=Call",
    )

if __name__ == "__main__":
  absltest.main()
